'use client';
/**
 * @fileOverview Institutional Deterministic Ingestion Hub v46.0.
 * FIXED: parseDeterministicBilingual upgraded to multi-line capture protocol.
 * FIXED: Diagram and Reasoning state machines hardened for same-line markers.
 */

export type ParserFormat = 
  | 'CURRENT_AFFAIRS' 
  | 'BILINGUAL_MCQ' 
  | 'ENGLISH_ONLY' 
  | 'PUNJABI_ONLY' 
  | 'MATHEMATICS' 
  | 'REASONING' 
  | 'DIAGRAM' 
  | 'TABLE' 
  | 'GRAPH' 
  | 'MATCHING' 
  | 'ASSERTION' 
  | 'FILL_BLANK' 
  | 'TRUE_FALSE';

export type ParserMode = 'PRODUCTION' | 'STRICT';

export const QUESTION_SENTINEL_REGEX = /^\s*(?:Q|Question|QUESTION|Q\.)\s?[-.]?\s?\d+(?:[\.\s:]|$)/i;

export function isQuestionStart(line: string): boolean {
  if (!line) return false;
  return QUESTION_SENTINEL_REGEX.test(line.trim());
}

const NOISE_PATTERNS = [
  /^Advertisement$/i, /^Advertisements$/i, /^Sponsored$/i, 
  /Download Our (Android |Mobile |iOS )?App/i, /Install App/i, /Get the App/i,
  /^Follow Us/i, /^Join Telegram/i, /^Telegram: @/i, 
  /WhatsApp (Channel|Group)/i, 
  /^(Website|Visit|Click Here|Subscribe|Source|Copyright|Generated on|Powered by|Generated by|Prepared by|Compiled by):/i,
  /^Generated on/i, /^Powered by/i, /^Generated by/i, /^Prepared by/i, 
  /^Compiled by/i, /^Source:/i, /^Copyright/i, 
  /^All Rights Reserved/i, /^Page\s*\d+/i,
  /^www\./i, /^https?:\/\//i, /^©/i,
  /^[-\s\.\*_=]{3,}$/,
  /^\s*[\.·,]{1,}\s*$/
];

const ANS_MARKERS = ["Answer", "Official Key", "Correct Answer", "ਉੱਤਰ", "उत्तर", "ਸਹੀ ਉੱਤਰ"];
const EXPL_MARKERS = ["Explanation", "Solution", "ਵਿਆਖਿਆ", "ਵਿਆਖਿਆ", "व्याख्या", "Rationale"];

export function preprocessText(text: string): string {
  if (!text) return "";
  const lines = text.split(/\r?\n/);
  const cleanLines = lines.filter(line => {
    const trimmed = line.trim();
    if (!trimmed) return true; 
    const isNoise = NOISE_PATTERNS.some(pattern => pattern.test(trimmed));
    return !isNoise;
  });
  return cleanLines.join('\n').trim();
}

function detectOptionMarker(line: string): { opt: 'A' | 'B' | 'C' | 'D', text: string } | null {
  const trimmed = line.trim();
  const patterns = [
    { regex: /^\s*[\(]?([A])[\)\.]\s*(.*)/i, val: 'A' },
    { regex: /^\s*[\(]?([B])[\)\.]\s*(.*)/i, val: 'B' },
    { regex: /^\s*[\(]?([C])[\)\.]\s*(.*)/i, val: 'C' },
    { regex: /^\s*[\(]?([D])[\)\.]\s*(.*)/i, val: 'D' },
    { regex: /^\s*[\(]?(1)[\)\.]\s*(.*)/, val: 'A' },
    { regex: /^\s*[\(]?(2)[\)\.]\s*(.*)/, val: 'B' },
    { regex: /^\s*[\(]?(3)[\)\.]\s*(.*)/, val: 'C' },
    { regex: /^\s*[\(]?(4)[\)\.]\s*(.*)/, val: 'D' },
    { regex: /^\s*[①❶]\s*(.*)/, val: 'A' },
    { regex: /^\s*[②❷]\s*(.*)/, val: 'B' },
    { regex: /^\s*[③❸]\s*(.*)/, val: 'C' },
    { regex: /^\s*[④❹]\s*(.*)/, val: 'D' }
  ];

  for (const p of patterns) {
    const match = trimmed.match(p.regex);
    if (match) return { opt: p.val as any, text: match[match.length - 1].trim() };
  }
  return null;
}

function parseDiagram(rawText: string, metadata: any) {
  const lines = rawText.split('\n');
  const questions: any[] = [];
  let currentQ: any = null;
  let state: 'BODY' | 'OPTIONS' | 'ANSWER' | 'EXPLANATION' | 'COMPLETE' = 'BODY';
  let bodySubState: 'INTRO' | 'DIAGRAM' | 'SUFFIX' = 'INTRO';
  
  const punjabiRegex = /[\u0A00-\u0A7F]/;

  const finalize = () => {
    if (!currentQ) return;
    ['englishQuestion', 'punjabiQuestion', 'englishQuestionSuffix', 'punjabiQuestionSuffix', 'diagramContent', 'englishExplanation', 'punjabiExplanation'].forEach(k => {
      if (currentQ[k]) currentQ[k] = currentQ[k].trim();
    });
    questions.push(currentQ);
    currentQ = null;
  };

  const isDiagramLine = (line: string, trimmed: string) => {
    if (trimmed === "") return true;
    if (/[│┌┐└┘├┤┬┴┼━┃┏┓┗┛┣┫┳┻╋→←↑↓▲▼◀▶]/.test(line)) return true;
    if (/[\|\-\+\_\=\\\/]{2,}/.test(line)) return true;
    if (/^(?:Yes|No|True|False|Start|End|Input|Output|Print|Read|Write|Step|Result)$/i.test(trimmed)) return true;
    if (trimmed.length < 25) return true;
    return false;
  };

  lines.forEach((line) => {
    const trimmed = line.trim();
    if (isQuestionStart(trimmed)) {
      finalize();
      state = 'BODY';
      bodySubState = 'INTRO';
      currentQ = {
        ...metadata,
        id: `q-diagram-${Math.random().toString(36).substr(2, 9)}`,
        questionType: 'IMAGE_BASED',
        englishQuestion: "", punjabiQuestion: "",
        englishQuestionSuffix: "", punjabiQuestionSuffix: "",
        diagramContent: "",
        optionAEnglish: "", optionBEnglish: "", optionCEnglish: "", optionDEnglish: "",
        correctAnswer: "",
        englishExplanation: "", punjabiExplanation: "",
        status: 'PUBLISHED'
      };
      
      const content = line.replace(QUESTION_SENTINEL_REGEX, '').trim();
      if (content) {
         if (punjabiRegex.test(content)) currentQ.punjabiQuestion = content;
         else currentQ.englishQuestion = content;
      }
      return;
    }

    if (!currentQ || state === 'COMPLETE') return;

    const opt = detectOptionMarker(line);
    const isAns = ANS_MARKERS.some(m => trimmed.toLowerCase().startsWith(m.toLowerCase()));
    const isExpl = EXPL_MARKERS.some(m => trimmed.toLowerCase().startsWith(m.toLowerCase()));

    if (opt) state = 'OPTIONS';
    else if (isAns) state = 'ANSWER';
    else if (isExpl) state = 'EXPLANATION';

    if (state === 'BODY') {
       const isDiagLine = isDiagramLine(line, trimmed);
       if (isDiagLine && bodySubState === 'INTRO') bodySubState = 'DIAGRAM';
       else if (!isDiagLine && bodySubState === 'DIAGRAM' && (trimmed.length > 30 || trimmed.endsWith('?'))) bodySubState = 'SUFFIX';

       if (bodySubState === 'INTRO') {
          if (punjabiRegex.test(line)) currentQ.punjabiQuestion += (currentQ.punjabiQuestion ? '\n' : '') + trimmed;
          else currentQ.englishQuestion += (currentQ.englishQuestion ? '\n' : '') + trimmed;
       } else if (bodySubState === 'DIAGRAM') {
          currentQ.diagramContent += (currentQ.diagramContent ? '\n' : '') + line;
       } else if (bodySubState === 'SUFFIX') {
          if (punjabiRegex.test(line)) currentQ.punjabiQuestionSuffix += (currentQ.punjabiQuestionSuffix ? '\n' : '') + trimmed;
          else currentQ.englishQuestionSuffix += (currentQ.englishQuestionSuffix ? '\n' : '') + trimmed;
       }
    } else if (state === 'OPTIONS' && opt) {
       currentQ[`option${opt.opt}English`] = opt.text;
    } else if (state === 'ANSWER') {
       const match = trimmed.match(/[A-D]/i);
       if (match) currentQ.correctAnswer = match[0].toUpperCase();
    } else if (state === 'EXPLANATION') {
       const clean = line.replace(/^(?:Explanation|Solution|ਵਿਆਖਿਆ|ਵਿਆਖਿਆ|व्याख्या|Rationale|Answer|Correct Answer|Official Key)\s*[:\-]?\s*/i, '').trim();
       if (!clean) return;
       if (punjabiRegex.test(clean)) currentQ.punjabiExplanation += (currentQ.punjabiExplanation ? '\n' : '') + clean;
       else currentQ.englishExplanation += (currentQ.englishExplanation ? '\n' : '') + clean;
    }
  });

  finalize();
  return { questions };
}

function parseReasoning(rawText: string, metadata: any) {
  const lines = rawText.split('\n');
  const questions: any[] = [];
  let state: 'SEARCH_QUESTION' | 'READ_QUESTION' | 'READ_OPTIONS' | 'READ_ANSWER' | 'READ_EXPLANATION' = 'SEARCH_QUESTION';
  let currentQ: any = null;
  let currentOption: 'A' | 'B' | 'C' | 'D' | null = null;
  const punjabiRegex = /[\u0A00-\u0A7F]/;
  const localKey = metadata.secondaryLanguage === 'hindi' ? 'hindiQuestion' : 'punjabiQuestion';
  const expLocalKey = metadata.secondaryLanguage === 'hindi' ? 'hindiExplanation' : 'punjabiExplanation';
  const locSuffix = metadata.secondaryLanguage === 'hindi' ? 'Hindi' : 'Punjabi';

  const finalizeQuestion = () => {
    if (!currentQ) return;
    Object.keys(currentQ).forEach(key => {
      if (typeof currentQ[key] === 'string') {
        currentQ[key] = currentQ[key].trim();
      }
    });
    questions.push(currentQ);
    currentQ = null;
  };

  lines.forEach((line) => {
    const trimmed = line.trim();
    if (NOISE_PATTERNS.some(pattern => pattern.test(trimmed))) return;
    if (isQuestionStart(trimmed)) {
      if (currentQ) finalizeQuestion();
      state = 'READ_QUESTION';
      currentQ = {
        ...metadata,
        id: `q-${Math.random().toString(36).substr(2, 9)}`,
        status: 'PUBLISHED',
        questionType: 'MCQ',
        englishQuestion: "", [localKey]: "",
        englishExplanation: "", [expLocalKey]: ""
      };
      const content = line.replace(QUESTION_SENTINEL_REGEX, '').trim();
      if (content) {
         if (punjabiRegex.test(content)) currentQ[localKey] = content;
         else currentQ.englishQuestion = content;
      }
      return;
    }
    if (!currentQ) return;
    const optMatch = detectOptionMarker(line);
    const isAnsMarker = ANS_MARKERS.some(m => trimmed.toLowerCase().startsWith(m.toLowerCase()));
    const isExplMarker = EXPL_MARKERS.some(m => trimmed.toLowerCase().startsWith(m.toLowerCase()));

    if (optMatch && (state === 'READ_QUESTION' || state === 'READ_OPTIONS')) {
      state = 'READ_OPTIONS';
      currentOption = optMatch.opt;
    } else if (isAnsMarker) {
      state = 'READ_ANSWER';
    } else if (isExplMarker) {
      state = 'READ_EXPLANATION';
    }

    if (state === 'READ_QUESTION') {
       if (trimmed === "") {
          currentQ.englishQuestion += '\n'; currentQ[localKey] += '\n';
       } else if (punjabiRegex.test(line)) {
          currentQ[localKey] += (currentQ[localKey] ? '\n' : '') + line;
       } else {
          currentQ.englishQuestion += (currentQ.englishQuestion ? '\n' : '') + line;
       }
    } 
    else if (state === 'READ_OPTIONS' && currentOption) {
      const engKey = `option${currentOption}English`;
      const locKeyField = `option${currentOption}${locSuffix}`;
      const text = optMatch ? optMatch.text : line;
      if (punjabiRegex.test(text)) currentQ[locKeyField] = (currentQ[locKeyField] || "") + (currentQ[locKeyField] ? "\n" : "") + text.trim();
      else currentQ[engKey] = (currentQ[engKey] || "") + (currentQ[engKey] ? "\n" : "") + text.trim();
    }
    else if (state === 'READ_ANSWER') {
      const match = trimmed.match(/(?:Answer|Official Key|Correct Answer|ਉੱਤਰ|उत्तर|ਸਹੀ ਉੱਤਰ)\s*[:\-]?\s*\(?([A-D1-4])\)?/i);
      if (match) {
        const val = match[1].toUpperCase();
        const map: any = { '1': 'A', '2': 'B', '3': 'C', '4': 'D' };
        currentQ.correctAnswer = map[val] || val;
      }
    }
    else if (state === 'READ_EXPLANATION') {
       const cleanLine = line.replace(new RegExp(`^(?:${EXPL_MARKERS.join('|')})\\s*[:\\-]?\\s*`, 'i'), '');
       if (punjabiRegex.test(cleanLine)) currentQ[expLocalKey] += (currentQ[expLocalKey] ? '\n' : '') + cleanLine;
       else currentQ.englishExplanation += (currentQ.englishExplanation ? '\n' : '') + cleanLine;
    }
  });

  finalizeQuestion();
  return { questions };
}

function parseDeterministicBilingual(rawText: string, metadata: any) {
  const blocks = rawText.split(/\n\s*\n/).filter(b => b.trim().length > 0);
  const questions: any[] = [];
  const locSuffix = metadata.secondaryLanguage === 'hindi' ? 'Hindi' : 'Punjabi';
  const punjabiRegex = /[\u0A00-\u0A7F]/;
  
  blocks.forEach(block => {
    const q: any = { 
      ...metadata, 
      id: `q-${Math.random().toString(36).substr(2, 9)}`, 
      status: 'PUBLISHED',
      englishQuestion: "",
      [`punjabiQuestion`]: "",
      [`hindiQuestion`]: ""
    };
    const lines = block.split('\n').map(l => l.trim()).filter(l => l.length > 0);
    let foundMarker = false;
    let foundOptions = false;

    lines.forEach(line => {
      const optMatch = detectOptionMarker(line);
      const isQ = isQuestionStart(line);

      if (isQ) {
        foundMarker = true;
        const content = line.replace(QUESTION_SENTINEL_REGEX, '').trim();
        if (content) {
           if (punjabiRegex.test(content)) q[`punjabiQuestion`] = content;
           else q.englishQuestion = content;
        }
      }
      else if (optMatch) {
         foundOptions = true;
         const engKey = `option${optMatch.opt}English`;
         const locKey = `option${optMatch.opt}${locSuffix}`;
         if (!q[engKey]) q[engKey] = optMatch.text;
         else if (q[engKey].trim() !== optMatch.text.trim()) q[locKey] = optMatch.text;
      }
      else if (foundMarker && !foundOptions) {
         if (punjabiRegex.test(line)) q[`punjabiQuestion`] = (q[`punjabiQuestion`] ? q[`punjabiQuestion`] + '\n' : '') + line;
         else q.englishQuestion = (q.englishQuestion ? q.englishQuestion + '\n' : '') + line;
      }
    });

    questions.push(q);
  });
  return { questions };
}

export function parseBulkQuestions(rawText: string, metadata: any) {
  if (!rawText || !rawText.trim()) return { questions: [] };
  if (metadata.parserFormat === 'DIAGRAM') return parseDiagram(rawText, metadata);
  if (metadata.parserFormat === 'REASONING') return parseReasoning(rawText, metadata);
  return parseDeterministicBilingual(rawText, metadata);
}

export function validateMCQSchema(q: any): { errors: string[], warnings: string[] } {
  const errors: string[] = [];
  const warnings: string[] = [];
  if (!q.englishQuestion && !q.punjabiQuestion && !q.hindiQuestion && !q.diagramContent) errors.push("Question content missing.");
  const optCount = ['A', 'B', 'C', 'D'].filter(l => (q[`option${l}English`] || "").trim() || (q[`option${l}Punjabi`] || "").trim() || (q[`option${l}Hindi`] || "").trim()).length;
  if (optCount < 4) errors.push("Less than four options detected.");
  if (!q.correctAnswer) errors.push("Answer missing.");
  return { errors, warnings };
}
