'use client';

import React, { useState, useEffect } from "react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { motion } from "framer-motion";
import { 
  Smartphone, 
  Download, 
  Sparkles, 
  ShieldCheck, 
  Zap, 
  ChevronRight,
  Info,
  Clock,
  CheckCircle2,
  AlertCircle
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";
import { cn } from "@/lib/utils";

/**
 * @fileOverview Official Direct APK Download Hub v3.0.
 * UPDATED: Optimized typography and direct download logic.
 */
export default function InstallPage() {
  const [mounted, setMounted] = useState(false);
  const [metadata, setMetadata] = useState<any>(null);

  useEffect(() => {
    setMounted(true);
    // Fetch build metadata automatically generated by GitHub Actions
    fetch('/apk/metadata.json')
      .then(res => res.json())
      .then(data => setMetadata(data))
      .catch(() => setMetadata({ version: "1.0.0", build: 1, updatedAt: new Date().toISOString() }));
  }, []);

  const handleDownload = () => {
    // Direct link to the APK hosted on the same domain
    window.location.href = "/apk/cracklix-production.apk";
  };

  if (!mounted) return null;

  return (
    <div className="min-h-[100dvh] bg-slate-50 font-body text-left overflow-x-hidden">
      <Navbar />
      
      <main className="container mx-auto px-4 py-12 md:py-24 max-w-6xl space-y-16 md:space-y-32">
        
        {/* HERO SECTION */}
        <div className="text-center space-y-6 max-w-4xl mx-auto">
           <motion.div 
             initial={{ scale: 0.8, opacity: 0 }}
             animate={{ scale: 1, opacity: 1 }}
             className="h-20 w-20 md:h-24 md:w-24 bg-primary/10 rounded-[2.5rem] flex items-center justify-center mx-auto text-primary shadow-2xl border border-primary/20"
           >
              <Zap className="h-10 md:h-12 fill-current" />
           </motion.div>
           <div className="space-y-4">
              <h1 className="text-4xl md:text-8xl font-[900] text-[#0F172A] tracking-tighter leading-[0.95] uppercase">
                Cracklix <br/> <span className="text-primary">Android</span>
              </h1>
              <p className="text-slate-500 font-medium text-base md:text-2xl max-w-2xl mx-auto leading-tight">
                 Download the official app for Punjab Government Exam preparation. No GitHub login required.
              </p>
           </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 md:gap-16 items-start">
           
           {/* DOWNLOAD CARD */}
           <div className="lg:col-span-7">
              <Card className="border-none shadow-5xl rounded-[3rem] bg-[#0B1528] text-white overflow-hidden p-8 md:p-16 space-y-12 relative group">
                 <div className="absolute top-0 right-0 p-12 opacity-5 rotate-12 group-hover:scale-110 transition-transform duration-1000">
                    <Smartphone className="h-64 w-64 md:h-96 md:w-96" />
                 </div>
                 
                 <div className="relative z-10 space-y-10">
                    <div className="flex items-center justify-between">
                       <Badge className="bg-primary text-white border-none px-4 py-1.5 rounded-full font-black uppercase text-[10px] tracking-widest shadow-xl">
                          STABLE RELEASE
                       </Badge>
                       {metadata && (
                         <div className="text-[10px] font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2">
                           <Clock className="h-3 w-3 text-primary" /> Updated: {new Date(metadata.updatedAt).toLocaleDateString()}
                         </div>
                       )}
                    </div>

                    <div className="space-y-8">
                       <div className="space-y-2">
                          <h2 className="text-3xl md:text-6xl font-black tracking-tight">V{metadata?.version || '1.0.0'}</h2>
                          <p className="text-slate-400 font-bold uppercase text-[10px] tracking-[0.4em]">Official Preparation Node</p>
                       </div>

                       <div className="space-y-6">
                          <p className="text-slate-400 text-base md:text-xl font-medium leading-relaxed">
                            Experience the full power of Cracklix with native performance, offline support, and high-fidelity mock attempts.
                          </p>
                          <div className="flex flex-col gap-4">
                             <Button 
                               onClick={handleDownload}
                               className="w-full h-16 md:h-24 bg-primary hover:bg-blue-700 text-white font-black uppercase text-xs md:text-lg tracking-[0.2em] rounded-[2rem] border-none shadow-4xl group active:scale-[0.98] transition-all"
                             >
                                <Download className="h-6 w-6 md:h-8 md:w-8 mr-4 group-hover:translate-y-1 transition-transform" /> 
                                Download APK
                             </Button>
                             <div className="flex items-center justify-center gap-6 text-slate-500 font-bold text-[10px] uppercase tracking-widest">
                                <span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-500" /> Size: ~12MB</span>
                                <span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-500" /> Build: #{metadata?.build || '---'}</span>
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </Card>
           </div>

           {/* SIDEBAR: GUIDES & PERKS */}
           <div className="lg:col-span-5 space-y-10 text-left">
              <div className="space-y-6">
                 <h3 className="text-[10px] font-black uppercase text-slate-400 tracking-[0.4em] ml-2">Installation Guide</h3>
                 <div className="space-y-3">
                    <GuideStep step="1" title="Download" desc="Click the button to start the APK transfer." />
                    <GuideStep step="2" title="Authorize" desc="Enable 'Install from Unknown Sources' if prompted." />
                    <GuideStep step="3" title="Initialize" desc="Open the app and sync your registry hub." />
                 </div>
              </div>

              <div className="p-8 bg-blue-50 rounded-[2.5rem] border border-blue-100 space-y-6 shadow-sm">
                 <div className="flex items-center gap-4">
                    <div className="h-10 w-10 bg-white rounded-xl flex items-center justify-center text-primary shadow-sm">
                       <AlertCircle className="h-5 w-5" />
                    </div>
                    <h4 className="font-black text-blue-900 uppercase text-sm">Safe & Secure</h4>
                 </div>
                 <p className="text-xs md:text-sm text-blue-700 font-medium leading-relaxed uppercase">
                    Every build is scanned by Google Play Protect and verified by Arsh Grewal Management for data integrity.
                 </p>
                 <div className="flex gap-2">
                    {['PSSSB', 'PPSC', 'Police'].map(hub => (
                       <Badge key={hub} className="bg-white border-blue-100 text-blue-400 text-[8px] font-black uppercase px-2">{hub} READY</Badge>
                    ))}
                 </div>
              </div>
           </div>
        </div>

        {/* FEATURE GRID */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 md:gap-12">
           <AppFeature icon={<Zap />} title="Low Latency" desc="Zero-delay response during mock test attempts." />
           <AppFeature icon={<Smartphone />} title="Mobile Native" desc="Intuitive gesture control and full-screen CBT mode." />
           <AppFeature icon={<CheckCircle2 />} title="Auto Sync" desc="Instant synchronization with your state merit rank." />
        </div>
      </main>

      <Footer />
    </div>
  );
}

function GuideStep({ step, title, desc }: any) {
   return (
      <div className="p-6 bg-white rounded-2xl border border-slate-100 shadow-xl flex items-start gap-6 group hover:translate-x-2 transition-all">
         <div className="h-10 w-10 rounded-xl bg-[#0F172A] text-white flex items-center justify-center font-black text-sm shrink-0 shadow-lg">
            {step}
         </div>
         <div className="space-y-1">
            <h4 className="font-black text-[#0F172A] uppercase text-xs md:text-sm">{title}</h4>
            <p className="text-[10px] md:text-xs text-slate-500 font-medium leading-tight">{desc}</p>
         </div>
      </div>
   );
}

function AppFeature({ icon, title, desc }: any) {
   return (
      <div className="p-10 rounded-[3rem] bg-white shadow-2xl border border-slate-100 text-center space-y-6 group hover:shadow-primary/5 transition-all">
         <div className="h-16 w-16 bg-slate-50 rounded-2xl flex items-center justify-center mx-auto text-primary shadow-inner group-hover:scale-110 transition-transform">
            {React.cloneElement(icon as React.ReactElement<any>, { className: "h-8 w-8" })}
         </div>
         <div className="space-y-2">
            <h3 className="font-black text-xl text-[#0F172A] uppercase">{title}</h3>
            <p className="text-slate-400 font-bold uppercase text-[9px] tracking-widest">{desc}</p>
         </div>
      </div>
   );
}
